name: WorldTpUI
main: Zero.WorldTpUI.Main
version: 0.0.2
api: [1.0.0]
author: ZeroDevOfficial
description: Allows Admins to tp between worlds with a simple UI in Nukkit

#Working on permissions

commands:
  wtpui:
    description: WorldTpUI command
    usage: "/wtpui"
    permission: WorldTpUI.command.wtpui
    permission-message: "You do not have the required permission to run /wtpui"
permissions:
  WorldTpUI:
    description: "Allows the user to run the wtpui command"
    default: true
